language: python
python: 
 - 2.7
 - 3.3
 - 3.4
install:
 - easy_install -U setuptools
 - python setup.py install
 - pip install nose coverage nose-testconfig
 - pip install coveralls
script: nosetests --nologcapture --config nose_cover.cfg --tc-file nose_travis.ini
after_success:
  coveralls
