language: python
python: 
 - "2.7"

#before_install:
# - sudo apt-get update
# - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr language-pack-nl
install:
 - easy_install -U setuptools
 - python setup.py install
 - pip install nose nose-testconfig


script:
 - "if [python = '2.7']; then 'nosetest --nologcapture --tc-file nose_travis.ini';else 'nosetest --tc-file nose_travis.ini';fi"

