language: python
python:
 - 2.6
 - 2.7
install:
 - python setup.py install
 - pip install nose
 # Install unittest2 on 2.6
 - "if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi"
script: nosetests
