language: python
python:
 - 2.7
 - 3.2
 - 3.3
install:
 - easy_install -U setuptools
 - python setup.py install
 - pip install nose nose-testconfig
script: nosetests --nologcapture --tc-file nose_travis.ini
