language: python
python: 2.7
#before_install:
# - sudo apt-get update
# - sudo apt-get --reinstall install -qq language-pack-en language-pack-fr language-pack-nl
install:
 - easy_install -U setuptools
 - python setup.py install
 - pip install nose nose-testconfig
env:
 - TOX_ENV=py27
 - TOX_ENV=py32
 - TOX_ENV=cover

script:
 - tox -e $TOX_ENV
