language: python
python: 
 - 2.7
 - 3.3
 - 3.4
install:
 - easy_install -U setuptools
 - python setup.py install
 - pip install nose coverage nose-testconfig
 - pip install coveralls

script: py.test --cov crabpy --cov-report term-missing --cov-config nose_cover.cfg -c nose_travis.ini tests/
after_success:
  coveralls
