sudo: false
language: python
python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
install:
 - easy_install -U setuptools
 - pip install -r requirements-dev.txt
 - python setup.py install
script: py.test --cov crabpy --cov-report term-missing -c pytest_travis.ini tests/
after_success:
  coveralls
