sudo: false
language: python
python:
 - 3.6
 - 3.8
install:
 - pip install -r requirements-dev.txt
 - python setup.py install
script: py.test --cov crabpy --cov-report term-missing -c pytest_travis.ini tests/
after_success:
  coveralls
