name: crabpy tests

on:
  pull_request:
    paths:
      - crabpy/**
      - tests/**
      - .github/workflows/backend.yaml
      - pyproject.toml
      - requirements*.txt

env:
  CRABPY_INTEGRATION_TESTS: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install python requirements
        run: |
          pip install pip-tools
          pip-sync requirements-dev.txt
          pip install -e .

      - name: Python tests
        run: |
          flake8
          pytest --cov=crabpy --cov-report=xml tests --crab-integration --capakey-integration

      - name: Code Coverage Report
        if: matrix.python-version == '3.11'
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.8
          thresholdModified: 0.8
